version: '3.9'

services:
  db:
    image: postgres
    privileged: true
    ports:
      - 5432:5432
    env_file:
      - backend/.env
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mihail"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    privileged: true
    ports:
      - 8000:8000
    command: "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/backend
  frontend:
    build: ./frontend
    ports:
      - 80:3000
    command: "npm start"
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend

volumes:
  pgdata: